# ------- Branding Related Config ------- #
# Keep in sync with config/installation_config.yml.
# On community plan, Internal::ReconcilePlanConfigService resets branding to these values.
- name: INSTALLATION_NAME
  value: 'INPERA Chat'
- name: LOGO_THUMBNAIL
  value: 'https://inpera.s3.amazonaws.com/logoPadrao/IconePadrao.png'
- name: LOGO
  value: 'https://inpera.s3.amazonaws.com/logoPadrao/INPERA-ESCURO(300x100).png'
- name: LOGO_DARK
  value: 'https://inpera.s3.amazonaws.com/logoPadrao/INPERA-ESCURO(300x100).png'
- name: BRAND_URL
  value: 'https://www.chatwoot.com'
- name: WIDGET_BRAND_URL
  value: 'https://www.chatwoot.com'
- name: BRAND_NAME
  value: 'INPERA Chat'
- name: TERMS_URL
  value: 'https://www.chatwoot.com/terms-of-service'
- name: PRIVACY_URL
  value: 'https://www.chatwoot.com/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
